updated

diff --git a/hgrep b/hgrep
--- a/hgrep
+++ b/hgrep
@@ -2,17 +2,101 @@
 #!/bin/bash
 
 
-while getopts lie: opt; do
-	case $opt in
-		l) 		line1=" i=1"; line2="\"\\033[31m\"i\":\"\"\\033[0m\","; line3=" \$0 ; i++"; ;;
-		i) 		set="IGNORECASE=1;";  ;;
-		e) 		pattern=$OPTARG; printer="print" ;;
-		\?)		echo -e "NON existent flag\nAccepted Flags: -l -i -e";
-				exit 1; ;;
+############################################################
+# Help                                                     #
+############################################################
+Help()
+{
+   # Display Help
+   echo
+   echo "The order to use flags is as follows"
+   echo
+   echo "Syntax: scriptTemplate [hgrep (-l and/or -i) -s "pattern"]"
+   echo "options:"
+   echo "-e     Pattern to search for"
+   echo "-l     Toggle line numbers"
+   echo "-i     Case-insensitive pattern search"
+   echo
+}
+
+Help2()
+{
+   # Display Help
+   echo
+   echo "The order to use flags is as follows"
+   echo
+   echo "Syntax: scriptTemplate [hgrep (-l and/or -i) -s "pattern"]"
+   echo "options:"
+   echo "-e     Pattern to search for"
+   echo "-l     Toggle line numbers"
+   echo "-i     Case-insensitive pattern search"
+   echo
+   echo
+   echo "Examples:"
+   echo
+   echo "Show "
+   echo
+}
+lflag=false
+iflag=false
+sflag=false
+Hflag=false
+no="#"
+while getopts ":h:H:lis:" opt; do
+	case $opt in			
+		h) 		# display Help
+				Help 
+				exit;;
+		H) 		headers=$OPTARG; Hflag=true; ;;
+		l) 		line1=" i=1"; line2="\"\\033[31m\"i\":\"\"\\033[0m\","; line3=" \$0 ; i++"; lflag=true; ;;
+		i) 		set="IGNORECASE=1;"; iflag=true;  ;;
+		s) 		pattern=$OPTARG; printer="print"; no=""; sflag=true; ;;
+		\?) 	# Invalid option
+				echo "Error: Invalid option"
+				Help2
+				exit;;
+		:)		echo "Option -$OPTARG requires an argument." >&2
+				Help
+				exit;;
 	esac
 done
 
-awk 'FNR<=1{print; next} BEGIN{IGNORECASE=0; '"$set"' '"$line1"' } gsub(/('"$pattern"')/, "\033[31m&\033[0m")  {'"$printer"' '"$line2"' '"$line3"'} '
+if ((OPTIND <= 2)) then
+    echo "Invalid arguments"
+	echo
+	Help
+	exit
+fi
 
 
+if [[ "$Hflag" == true ]]
+then
+	re='^[0-9]+$'
+	if [[ ! "$headers" =~ $re ]] # || [[ "$headers" == "" ]]
+	then
+		echo "H not sufficient"
+		Help2
+		exit
+	elif [[ "$headers" == "" ]]
+	then
+		echo "H not sufficient"
+		Help2
+		exit
+	elif [[ "$headers" =~ $ri ]]
+	then
+		echo "H is sufficient"
+	fi
+fi
 
+if (( "$sflag" == true )) 
+then
+	awk 'FNR<=1{print; next} BEGIN{IGNORECASE=0; '"$set"' '"$line1"' } gsub(/('"$pattern"')/, "\033[31m&\033[0m")  {'"$printer"' '"$line2"' '"$line3"'} '
+else
+	Help
+	exit
+fi
+
+
+		#m) 		headers=$OPTARG; Hflag=true; ;;
+
+# if (( "$lflag" == true || "$iflag" == true && "$eflag" == true )) 
