search pattern without needing --search option

diff --git a/hgrep b/hgrep
--- a/hgrep
+++ b/hgrep
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-
-
 # Help                                                     #
 ############################################################
 Help()
@@ -27,6 +25,7 @@ Help()
    echo "Example syntax: hgrep -H 2 -li -f /etc/hosts -e "example.com" -e "acme.com" "
    echo 
    echo "More Examples: "
+   echo "lsblk | hgrep sda "
    echo "lsblk | hgrep -H 1 -lis nvme0n1"
    echo "hgrep -f /etc/hosts -H 5 -li -e "example.com" -e "acme.com" "
    echo
@@ -59,12 +58,22 @@ NoInput()
 {
    # Display NoInput
    echo
-   echo "Need to pass a file or command use -h for help"
+   echo "Need to pass a file or command use "hgrep -h" for help"
+   echo
 }
+
 tooMany()
 {
-   echo "Invalid combination of options -- "$@"  "
-   Help
+   echo 'Invalid combination of options --   '
+   echo "Type "hgrep -h" for help"
+   echo
+}
+
+tooManySearch()
+{
+   echo "Can only search for a single pattern unless "-e or --multi-search" is specified"
+   echo "Type "hgrep -h" for help"
+   echo
 }
 
 lflag=false
@@ -101,7 +110,7 @@ while true; do
 		-H | --headers) 		     headers="$2"; Hflag=true; shift 2  ;;
 		-l | --lines) 		        line1=" i=1"; line2="\"\\033[31m\"i\":\"\"\\033[0m\","; line3=" \$0 ; i++"; lflag=true; shift ;;
 		-i | --ignore-case) 	     set="IGNORECASE=1;"; iflag=true; shift  ;;
-		-s | --search) 	        if [[ "$sflag" == false ]]; then sflag=true; else tooMany; exit; fi; pattern="$2"; printer="print"; no="";  shift 2 ;;
+		-s | --search) 	        if [[ "$sflag" == false ]]; then sflag=true; else tooMany; exit 1; fi; pattern="$2"; printer="print"; no="";  shift 2 ;;
 		-e | --multi-search) 	  entries+=("$2"); eflag=true; printer="print"; shift 2  ;;
 		#-F)                      Fflag=true; ;;
       -f | --file)              if [[ "$fflag" == false ]]; then myfile="$2"; fflag=true; shift 2; else tooMany; exit 1; fi; ;;
@@ -129,10 +138,9 @@ fi
 
 # echo $OPTIND
 
-if [[ "$sflag" == true ]] && [[ "$eflag" == true ]]
+if [[ "$sflag" == true && "$eflag" == true ]]
 then
-   echo "Invalid combination of arguments -s -e"
-   Help
+   tooMany
    exit 1
 fi
 
@@ -141,7 +149,7 @@ if [[ "$Hflag" == true ]]
 then
    # Check if header argument is a positive numberical value
    re='^[0-9]+$'
-	if [[ ! "$headers" =~ $re ]] || [[ "$headers" == "" ]]
+	if [[ ! "$headers" =~ $re || "$headers" == "" ]]
 	then
 		echo "Not a valid argument for (-H | --headers)option, need positive integer '0-9'"
 		Help
@@ -200,7 +208,7 @@ done
 entries2=$(echo "${entries[@]}" | sed "s/[()]//g")
 #String Filtering
 string="$entries2"
-if [[ "$entries2" == "\\" ]] || [[ "$pattern" == "\\" ]]; then
+if [[ "$entries2" == "\\" || "$pattern" == "\\" ]]; then
    echo "does equal"
    echo "Search pattern cannot be double backlash"
    echo "Try four backslashes to search for literal backslashes"
@@ -222,18 +230,26 @@ entries=$(echo "$entries" | sed "s/\s//g")
 # echo "HERE"
 # echo "$entries"
 
-
-if [[ "$sflag" == true ]] || [[ "$eflag" == true ]] && [[ ! "$pattern" == '' ]] || [[ ! "$entries" == '' ]]
+# Check if used -s flag to specify search; If not then assume that the input after hgrep [NY OPTIONS] IS the search pattern
+if [[ "$sflag" == true && "$pattern" != '' ]]  ||  [[ "$eflag" == true  && "$entries" != '' ]]
 then
-   : # no-op
+   : # no-op and continue
+# Check that we don't have multiple search patterns seperated by spaces; $2 is the second input
+elif [[ "$sflag" == false  &&  "$eflag" == false  && $2 == '' && "$pattern" == '' ]]
+then
+   # echo "assigning $1 to pattern"
+   pattern=$1
+   printer="print"
 else
-   echo "Search pattern cannot be empty type -h for help"
+   tooManySearch
    exit 1
 fi
 
+
 # echo "${entries[@]}"
 
-if [[ "$sflag" == true ]] || [[  "$eflag" == true ]]
+# if [[ "$sflag" == true ]] || [[  "$eflag" == true ]]
+if [[ "$pattern" != '' ]]
 then
    if [[ "$fflag" == true ]]
    then
@@ -242,8 +258,8 @@ then
       awk 'FNR<='"$headers"'{print; next} BEGIN{IGNORECASE=0; '"$set"' '"$line1"' } gsub(/'"${entries//\//\\/}"''"${pattern//\//\\/}"'/, "\033[31m&\033[0m")  {'"$printer"' '"$line2"' '"$line3"'}'
    fi
 else
-	Help
-	exit
+	NoInput
+	exit 1
 fi
 
 # Multiple Entries  (sadf)|(asdf)|(asd)
