test

diff --git a/hgrep b/hgrep
--- a/hgrep
+++ b/hgrep
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 
-############################################################
+
 # Help                                                     #
 ############################################################
 Help()
@@ -74,53 +74,49 @@ or=''
 
 # NOTE: This requires GNU getopt.  On Mac OS X and FreeBSD, you have to install this
 # separately; see below.
-while getopts ":h::f:H:lis:li:e:-:" opt; do
-   # support long options: https://stackoverflow.com/a/28466267/519360
-   if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
-      OPT="${OPTARG%%=*}"       # extract long option name
-      OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
-      OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
-   fi
-	case $opt in			
-		h | help) 	      # display Help
-				            Help 
-				            exit;;
-		H | headers) 		headers=$OPTARG; Hflag=true; ;;
-		l | lines) 		           line1=" i=1"; line2="\"\\033[31m\"i\":\"\"\\033[0m\","; line3=" \$0 ; i++"; lflag=true; ;;
-		i | ignore-case) 	       set="IGNORECASE=1;"; iflag=true;  ;;
-		s | search-pattern) 		 pattern=$OPTARG; printer="print"; no=""; sflag=true; ;;
-		e | multi-search) 		 entries+=($OPTARG); eflag=true; printer="print";  ;;
-		#F)               Fflag=true; ;;
-      f | file)                myfile=$OPTARG; fflag=true; ;;
-      \?) 	            # Invalid option
-                        qflag=true
-                        echo "Error: Invalid option detected -$OPTARG"
-                        Help
-                        exit;;
-      :)		echo "Option -$OPTARG requires an argument." >&2
-                        Help
-                        exit;;
+TEMP=$(getopt -o hfHlise: --long help,file,headers,lines,ignore-case,search,lines,ignore-case,multi-search: \
+              -n 'hgrep' -- "$@" )
+
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+# Note the quotes around '$TEMP': they are essential!
+eval set -- "$TEMP"
+
+while true; do	
+   case "$1" in
+		-h | --help) 	           # display help
+                                Help
+				                    exit;;
+		-H | --headers) 		     headers="$2"; Hflag=true; shift 2 ;;
+		-l | --lines) 		        line1=" i=1"; line2="\"\\033[31m\"i\":\"\"\\033[0m\","; line3=" \$0 ; i++"; lflag=true; shift ;;
+		-i | --ignore-case) 	     set="IGNORECASE=1;"; iflag=true; shift  ;;
+		-s | --search) 	        pattern="$2"; printer="print"; no=""; sflag=true; shift 2 ;;
+		-e | --multi-search) 	  entries+=($OPTARG); eflag=true; printer="print"; shift 2  ;;
+		#-F)                      Fflag=true; ;;
+      -f | --file)              myfile=$OPTARG; fflag=true; shift 2 ;;
+      -- ) shift; break ;;
+       * ) break ;;
 	esac
 done
-shift $((OPTIND-1)) # remove parsed options and args from $@ list
 echo "$OPTIND"
 shift $(( OPTIND + 0))
 
 # echo "HERE HERE"
 # echo $OPTIND
 
-if (( OPTIND <= 2 ))
-then
-   echo "Not Enough arguments"
-	echo
-	Help
-	exit
-elif (( OPTIND > 2)) && [[ "$qflag" == true ]]
-then
-   echo "Error: Invalid option detected"
-   Help
-   exit
-fi
+
+# if (( OPTIND <= 2 ))
+# then
+#    echo "Not Enough arguments"
+# 	echo
+# 	Help
+# 	exit
+# elif (( OPTIND > 2)) && [[ "$qflag" == true ]]
+# then
+#    echo "Error: Invalid option detected"
+#    Help
+#    exit
+# fi
 
 if [[ "$sflag" == true ]] && [[ "$eflag" == true ]]
 then
@@ -129,6 +125,7 @@ then
    exit
 fi
 
+#Check if headers option is set
 if [[ "$Hflag" == true ]]
 then
 	re='^[0-9]+$'
